# Generated by Django 3.2 on 2023-06-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=50, verbose_name='Символьный код')),
                ('name', models.TextField(max_length=50, verbose_name='Наименование монеты')),
                ('price', models.FloatField(verbose_name='Текущий курс')),
                ('timestamp', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('total_supply', models.IntegerField(verbose_name='Объем торгов')),
                ('percent_change', models.FloatField(verbose_name='% изменения')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
