# Generated by Django 3.2 on 2023-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=256, verbose_name='Автор публикации')),
                ('description', models.TextField(verbose_name='Текст публикации')),
                ('title', models.TextField(max_length=256, verbose_name='Заголовок публикации')),
                ('published', models.DateField(db_index=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='coin',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
